controller_manager:
  ros__parameters:
    update_rate: 100

joint_state_broadcaster:
  ros__parameters: {}

skid_steer_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names:
      - wheel_front_left_joint
      - wheel_rear_left_joint
    right_wheel_names:
      - wheel_front_right_joint
      - wheel_rear_right_joint
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    enable_odom_tf: true
    publish_rate: 50
    wheel_separation: 0.4  # approx front to rear lateral distance
    wheel_radius: 0.05
